### ISSUE TITLE
Add support  for WPILib Camera Streams

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/DotNetDash#5]
The new camera streams from WPILib support a lot more features that we should support. Some are there, but this is discussion for whats left. Moved from https://github.com/robotdotnet/DotNetDash/commit/74a5b890b94e501431b1fd4a7b9355260c496221#commitcomment-20334419

**Comment by jkoritzinsky** [comment]
I don't have a USB camera. I've been using an MJPEG stream I have access to and reading the code to get table names.

**Comment by jkoritzinsky** [comment]
Table Names have been fixed everywhere.

**Comment by jkoritzinsky** [comment]
@ThadHouse The streams are now in subgroups under their camera names. Can you take a look and let me know if there's anything I'm missing?

**Comment by ThadHouse** [comment]
![streams](https://cloud.githubusercontent.com/assets/7727148/21583471/2227cfd8-d037-11e6-8e62-4e1f1b643765.PNG)

Yup steams work. Still can't get any video output however. I can break on the creation of the CameraView and that works correctly. However neither the USB stream, nor the MJPEG streams show anything on my computer.

**Comment by ThadHouse** [comment]
Also I don't know exactly what create the garbage in the URL, but the same thing shows up in SmartDashboard and OutlineViewer, and I can still copy that URL into chrome and it works, along with the view creation not throwing an exception, so it shouldn't be an issue.

**Comment by jkoritzinsky** [comment]
Can you try the newest master to see if you get the video showing?

**Comment by ThadHouse** [comment]
Yup. It displays now. That's cool. I got the new docs site up and running too, so we should be able to add a doc page for this as well fairly easily.
